check mongo output

diff --git a/.github/workflows/build-test-workflow.yml b/.github/workflows/build-test-workflow.yml
--- a/.github/workflows/build-test-workflow.yml
+++ b/.github/workflows/build-test-workflow.yml
@@ -109,64 +109,64 @@ jobs:
         include:
           - folder: 'game'
 
-  steps:
-    # - name: Show open ports BEFORE
-    #   run: netstat -tulpn | grep LISTEN
+    steps:
+      # - name: Show open ports BEFORE
+      #   run: netstat -tulpn | grep LISTEN
 
-    - name: Start MongoDB
-      run: |
-        docker run -e MONGO_INITDB_ROOT_USERNAME=testuser -e MONGO_INITDB_ROOT_PASSWORD=testpass -e MONGO_INITDB_DATABASE=starfish-test -d -p 27017:27017 mongo:5.0
+      - name: Start MongoDB
+        run: |
+          docker run -e MONGO_INITDB_ROOT_USERNAME=testuser -e MONGO_INITDB_ROOT_PASSWORD=testpass -e MONGO_INITDB_DATABASE=starfish-test -d -p 27017:27017 mongo:5.0
 
-    - name: Show open ports AFTER
-      run: netstat -tulpn | grep LISTEN
+      - name: Show open ports AFTER
+        run: netstat -tulpn | grep LISTEN
 
-    - name: Run mongosh and see if it connects
-      run: |
-        mongosh --eval 'db.getSiblingDB("starfish-test").getCollectionNames()' > output.json
+      - name: Run mongosh and see if it connects
+        run: |
+          mongosh --eval 'db.getSiblingDB("starfish-test").getCollectionNames()' > output.json
 
-    - name: Run mongosh and see if it connects
-      run: |
-        mongosh --host localhost --port 27017 --username testuser --password testpass --db starfish-test --eval 'db.getSiblingDB("starfish-test").getCollectionNames()' > output.json
+      - name: Run mongosh and see if it connects
+        run: |
+          mongosh --host localhost --port 27017 --username testuser --password testpass --db starfish-test --eval 'db.getSiblingDB("starfish-test").getCollectionNames()' > output.json
 
-    - name: Check output
-      run: cat output.json
+      - name: Check output
+        run: cat output.json
 
-    - name: Check Out Repo
-      uses: actions/checkout@v2
+      - name: Check Out Repo
+        uses: actions/checkout@v2
 
-    - name: Use Node.js
-      uses: actions/setup-node@v2.4.1
-      with:
-        node-version: '16'
+      - name: Use Node.js
+        uses: actions/setup-node@v2.4.1
+        with:
+          node-version: '16'
 
-    - uses: c-hive/gha-npm-cache@v1
+      - uses: c-hive/gha-npm-cache@v1
 
-    - name: NPM install on ${{matrix.folder}}
-      run: npm install
-      working-directory: ${{matrix.folder}}
+      - name: NPM install on ${{matrix.folder}}
+        run: npm install
+        working-directory: ${{matrix.folder}}
 
-    - name: Run test suite on ${{matrix.folder}}
-      run: npm run teststaging
-      working-directory: ${{matrix.folder}}
+      - name: Run test suite on ${{matrix.folder}}
+        run: npm run teststaging
+        working-directory: ${{matrix.folder}}
 
-    - uses: actions/upload-artifact@v2 # upload test results
-      if: success() || failure() # run this step even if previous step failed
-      with:
-        name: test-results
-        path: ${{matrix.folder}}/reports/test-results.json
+      - uses: actions/upload-artifact@v2 # upload test results
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: test-results
+          path: ${{matrix.folder}}/reports/test-results.json
 
-    - name: Download test result artifact
-      uses: actions/download-artifact@v2
-      if: success() || failure()
-      with:
-        name: test-results
+      - name: Download test result artifact
+        uses: actions/download-artifact@v2
+        if: success() || failure()
+        with:
+          name: test-results
 
-    - uses: dorny/test-reporter@v1
-      if: (success() || failure()) && (${{ github.actor }} != 'dependabot')
-      with:
-        name: test-results
-        path: ${{matrix.folder}}/reports/test-results.json
-        reporter: mocha-json
+      - uses: dorny/test-reporter@v1
+        if: (success() || failure()) && (${{ github.actor }} != 'dependabot')
+        with:
+          name: test-results
+          path: ${{matrix.folder}}/reports/test-results.json
+          reporter: mocha-json
 
   # TODO: Add cypress tests
 
