try cat action?

diff --git a/.github/workflows/build-test-workflow.yml b/.github/workflows/build-test-workflow.yml
--- a/.github/workflows/build-test-workflow.yml
+++ b/.github/workflows/build-test-workflow.yml
@@ -112,24 +112,33 @@ jobs:
 
       - name: Verify frontend server is running
         run: |
-          curl --silent http://localhost:80 > ./webserver_response.log
-          cat ./webserver_response.log
+          curl --silent http://localhost:80 --output ./webserver_response.log
+          curl --silent https://localhost:443 --output ./webserver_response2.log
+          curl --silent http://localhost:4200 --output ./webserver_response3.log
+          curl --silent http://localhost:4300 --output ./webserver_response4.log
 
-          curl --silent https://localhost:443 > ./webserver_response2.log
-          cat ./webserver_response2.log
+      - uses: pCYSl5EDgo/cat@master
+        with:
+          path: ./webserver_response.log
 
-          curl --silent http://localhost:4200> ./webserver_response3.log
-          cat ./webserver_response3.log
+      - uses: pCYSl5EDgo/cat@master
+        with:
+          path: ./webserver_response1.log
 
-          curl --silent http://localhost:4300> ./webserver_response4.log
-          cat ./webserver_response4.log
+      - uses: pCYSl5EDgo/cat@master
+        with:
+          path: ./webserver_response2.log
 
-          if grep -q "200" ./webserver_response.log; then
-            echo "Successfully deployed to CI"
-          else
-            echo "Failed to deploy to CI"
-            exit 1
-          fi
+      - uses: pCYSl5EDgo/cat@master
+        with:
+          path: ./webserver_response3.log
+
+          # if grep -q "200" ./webserver_response.log; then
+          #   echo "Successfully deployed to CI"
+          # else
+          #   echo "Failed to deploy to CI"
+          #   exit 1
+          # fi
 
   npm-test:
     # needs: [run-docker-compose]
