add web request test to build-test

diff --git a/.github/workflows/build-test-workflow.yml b/.github/workflows/build-test-workflow.yml
--- a/.github/workflows/build-test-workflow.yml
+++ b/.github/workflows/build-test-workflow.yml
@@ -168,6 +168,22 @@ jobs:
           exit 0
         shell: bash {0}
 
+      - name: Verify frontend returns 200
+        run: |
+          curl --write-out '%{http_code}' \
+          --silent \
+          --output ./webserver_response.log \
+          --request GET
+          --url 'https://localhost:4300`
+
+          cat ./webserver_response.log
+
+          if grep -q "200" ./webserver_response.log; then
+            echo "Successfully deployed to CI"
+          else
+            echo "Failed to deploy to CI"
+            exit 1
+          fi
   npm-test:
     # needs: [run-docker-compose]
     runs-on: ubuntu-latest
