add echos

diff --git a/.github/workflows/build-test-workflow.yml b/.github/workflows/build-test-workflow.yml
--- a/.github/workflows/build-test-workflow.yml
+++ b/.github/workflows/build-test-workflow.yml
@@ -111,36 +111,50 @@ jobs:
         run: netstat -tulpn | grep LISTEN
 
       - name: Verify frontend server is running
-        run: |
-          curl --silent http://localhost:80 --output ./webserver_response1.log &
-          curl --silent https://localhost:443 --output ./webserver_response2.log & 
-          curl --silent http://localhost:4200 --output ./webserver_response3.log &
-          curl --silent http://localhost:4300 --output ./webserver_response4.log & 
-          sleep 5
-          exit 0
-
-      - uses: pCYSl5EDgo/cat@master
+        uses: wei/curl@master
+        id: curl1
         with:
-          path: ./webserver_response1.log
+          args: http://localhost:80
 
-      - uses: pCYSl5EDgo/cat@master
+      - name: Verify frontend server is running
+        uses: wei/curl@master
+        id: curl2
         with:
-          path: ./webserver_response2.log
+          args: https://localhost:443
 
-      - uses: pCYSl5EDgo/cat@master
+      - name: Verify frontend server is running
+        uses: wei/curl@master
+        id: curl3
         with:
-          path: ./webserver_response3.log
+          args: http://localhost:4200
 
-      - uses: pCYSl5EDgo/cat@master
+      - name: Verify frontend server is running
+        uses: wei/curl@master
+        id: curl4
         with:
-          path: ./webserver_response4.log
+          args: http://localhost:4300
+        # run: |
+        #   curl --silent http://localhost:80 --output ./webserver_response1.log &
+        #   curl --silent https://localhost:443 --output ./webserver_response2.log &
+        #   curl --silent http://localhost:4200 --output ./webserver_response3.log &
+        #   curl --silent http://localhost:4300 --output ./webserver_response4.log &
+        #   sleep 5
+        #   exit 0
 
-          # if grep -q "200" ./webserver_response.log; then
-          #   echo "Successfully deployed to CI"
-          # else
-          #   echo "Failed to deploy to CI"
-          #   exit 1
-          # fi
+      - echo: '{{ curl1 }}'
+
+      - echo: '{{ curl2 }}'
+
+      - echo: '{{ curl3 }}'
+
+      - echo: '{{ curl4 }}'
+
+        # if grep -q "200" ./webserver_response.log; then
+        #   echo "Successfully deployed to CI"
+        # else
+        #   echo "Failed to deploy to CI"
+        #   exit 1
+        # fi
 
   npm-test:
     # needs: [run-docker-compose]
