Feature/update workflows (#543)

diff --git a/.github/workflows/build-test-workflow.yml b/.github/workflows/build-test-workflow.yml
--- a/.github/workflows/build-test-workflow.yml
+++ b/.github/workflows/build-test-workflow.yml
@@ -5,7 +5,7 @@ on:
     branches:
       - '*'
 jobs:
-  docker-build-publish:
+  docker-build-push:
     runs-on: ubuntu-latest
     strategy:
       matrix:
@@ -61,13 +61,13 @@ jobs:
 
       - uses: docker/build-push-action@v2
         if: steps.changes.outputs.src == 'true'
-        id: docker_build
+        id: dockerbuild
         with:
           context: .
           builder: ${{ steps.buildx.outputs.name }}
           file: ${{ matrix.dockerfile }}
           push: true
-          tags: starfishgame/${{ matrix.image }}:pull-request-${{ github.event.number }}, starfishgame/${{ matrix.image }}:staging-latest
+          tags: starfishgame/${{ matrix.image }}:pull-request-${{ github.event.number }}, starfishgame/${{ matrix.image }}:ci-latest
           cache-from: type=local,src=/tmp/.buildx-cache
           cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
 
@@ -77,8 +77,8 @@ jobs:
           rm -rf /tmp/.buildx-cache
           mv /tmp/.buildx-cache-new /tmp/.buildx-cache
 
-  run-docker-compose:
-    needs: [docker-build-publish]
+  docker-compose-run-verify:
+    needs: [docker-build-push]
     runs-on: ubuntu-latest
     steps:
       - name: Check Out Repo
@@ -102,14 +102,73 @@ jobs:
           echo "PULL_REQUEST_NUMBER=${{ github.event.number }}" >> .env
 
       - name: Launch containers
-        run: docker-compose -f docker-compose-staging.yml --env-file .env up -d
+        run: docker-compose -f docker-compose-ci.yml --env-file .env up -d
 
       - name: Show running containers
         run: docker ps
 
-      - name: Show open ports
-        run: netstat -tulpn | grep LISTEN
+      - name: Check for listening game/db/frontend ports
+        run: netstat -tulpn | grep -E "4200|27017|4300"
 
+      - name: Show container logs
+        run: |
+          for image in game db frontend discord nginx; do
+            echo "$image" && docker logs $image && echo "------------"
+          done
+
+      - name: Check frontend and game ports with telnet
+        run: |
+          sleep 10
+          echo "Checking port 4200" | telnet localhost 4200 > gameport.txt 
+          grep Connected gameport.txt
+          gameport_up=$?
+
+          if [ "$gameport_up" -eq "1" ]; then
+            echo "Game port is not open"
+          else
+            echo "Game port is open"
+          fi
+          echo "============"
+
+          echo "Checking port 4300" | telnet localhost 4300 > frontendport.txt
+          grep Connected frontendport.txt
+          frontendport_up=$?
+
+          if [ "$frontendport_up" -eq "1" ]; then
+            echo "Frontend port is not open"
+          else
+            echo "Frontend port is open"
+          fi
+
+          if [ "$frontendport_up" -eq "1" ]; then
+            exit 1
+          fi
+
+          if [ "$gameport_up" -eq "1" ]; then
+            exit 1
+          fi
+
+          exit 0
+        shell: bash {0}
+
+      - name: Verify CI deployment
+        run: |
+          curl --silent --output ./webserver_response.log --request GET http://localhost:4300
+
+          cat ./webserver_response.log
+
+          grep "<title>Starfish</title>" ./webserver_response.log
+          found_title=$?
+
+          grep "502 Bad Gateway" ./webserver_response.log
+          found_badgateway=$?
+          if [[ $found_title -eq "0" && $found_badgateway -eq "1" ]]; then
+            echo "Successfully deployed to CI."
+          else
+            echo "Failed to deploy to CI."
+            # exit 1
+          fi
+        shell: bash {0}
   npm-test:
     # needs: [run-docker-compose]
     runs-on: ubuntu-latest
@@ -119,15 +178,12 @@ jobs:
           - folder: 'game'
 
     steps:
-      # - name: Show open ports BEFORE
-      #   run: netstat -tulpn | grep LISTEN
-
       - name: Check Out Repo
         uses: actions/checkout@v2
 
       - name: Start MongoDB
         run: |
-          docker build -t mongo-test -f db/Dockerfile-staging .
+          docker build -t mongo-test -f db/Dockerfile-ci .
           docker run -d -p 0.0.0.0:27017:27017 mongo-test
 
       - name: Use Node.js
@@ -144,7 +200,7 @@ jobs:
           working-directory: 'common'
 
       - name: Run test suite on ${{matrix.folder}}
-        run: npm run teststaging
+        run: npm run testci
         working-directory: ${{matrix.folder}}
 
       - uses: actions/upload-artifact@v2 # upload test results
@@ -169,7 +225,7 @@ jobs:
           reporter: mocha-json
 
   # TODO: Add cypress tests
-
+  #
   # artillery:
   #   needs: [run-docker-compose]
   #   runs-on: ubuntu-latest
